# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'for_tests.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Third_okno(object):
    def setupUi(self, Third_okno):
        Third_okno.setObjectName("Third_okno")
        Third_okno.resize(925, 621)
        self.label = QtWidgets.QLabel(Third_okno)
        self.label.setGeometry(QtCore.QRect(20, 30, 881, 171))
        self.label.setObjectName("label")
        self.radioButton_2 = QtWidgets.QRadioButton(Third_okno)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 210, 861, 51))
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup = QtWidgets.QButtonGroup(Third_okno)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(Third_okno)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 330, 861, 51))
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(Third_okno)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 270, 861, 51))
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup.addButton(self.radioButton_4)
        self.label_2 = QtWidgets.QLabel(Third_okno)
        self.label_2.setGeometry(QtCore.QRect(20, 500, 871, 101))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Third_okno)
        self.pushButton.setGeometry(QtCore.QRect(40, 400, 361, 91))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Third_okno)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 400, 361, 91))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Third_okno)
        QtCore.QMetaObject.connectSlotsByName(Third_okno)

    def retranslateUi(self, Third_okno):
        _translate = QtCore.QCoreApplication.translate
        Third_okno.setWindowTitle(_translate("Third_okno", "Form"))
        self.label.setText(_translate("Third_okno", "TextLabel"))
        self.radioButton_2.setText(_translate("Third_okno", "RadioButton"))
        self.radioButton_3.setText(_translate("Third_okno", "RadioButton"))
        self.radioButton_4.setText(_translate("Third_okno", "RadioButton"))
        self.label_2.setText(_translate("Third_okno", "TextLabel"))
        self.pushButton.setText(_translate("Third_okno", "Проверить ответ"))
        self.pushButton_2.setText(_translate("Third_okno", "Продолжить тест"))
