# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tests.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(816, 618)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(240, 40, 331, 41))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(190, 120, 411, 61))
        self.pushButton.setStyleSheet("font: 16pt \"MS Shell Dlg 2\"; \n"
"background-color: rgb(189, 236, 248);")
        self.pushButton.setObjectName("pushButton")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 210, 411, 61))
        self.pushButton_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\"; \n"
"background-color: rgb(243, 250, 163);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.buttonGroup.addButton(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 300, 411, 61))
        self.pushButton_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(225, 196, 169);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.buttonGroup.addButton(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 390, 411, 61))
        self.pushButton_4.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(186, 249, 168);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.buttonGroup.addButton(self.pushButton_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#000032;\">Выберете тест:</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Тест №1 (История)"))
        self.pushButton_2.setText(_translate("Form", "Тест №2 (Природа)"))
        self.pushButton_3.setText(_translate("Form", "Тест №3 (Население)"))
        self.pushButton_4.setText(_translate("Form", "Тест №4 (Другое)"))
